import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Reads .env at the repo root and writes src/env.js, which the app loads
// before src/config.js so window.__OBJECTFLIX_ENV__ is available everywhere.
// src/env.js is gitignored (it contains real secrets).

const root = new URL("..", import.meta.url);
const envPath = join(root.pathname.replace(/^\/([A-Za-z]:)/, "$1"), ".env");
const outPath = join(root.pathname.replace(/^\/([A-Za-z]:)/, "$1"), "src", "env.js");

const KEYS = ["GEMINI_API_KEY", "DISCORD_CLIENT_ID", "DISCORD_CLIENT_SECRET", "ARG_SECRET"];

const values = {};
for (const key of KEYS) values[key] = "";

try {
  const text = readFileSync(envPath, "utf8");
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    if (KEYS.includes(key)) values[key] = trimmed.slice(eq + 1).trim();
  }
} catch {
  // No .env — write empty placeholders so the app keeps working.
}

const body = `// GENERATED by scripts/gen-env.js - do not edit. This file is gitignored.
window.__OBJECTFLIX_ENV__ = Object.freeze(${JSON.stringify(values, null, 2)});
`;

writeFileSync(outPath, body, "utf8");
const empty = KEYS.every((k) => !values[k]);
console.log(empty ? "src/env.js written (all values empty — did you create .env?)" : "src/env.js written from .env");
